name: FakeDimension
main: fakedimension.FakeDimension
api-version: 1.16
depend: [ProtocolLib]
version: 1.3
author: _Shevchik_
commands:
    fakedimension:
        description: Reload command for FakeDimension
        usage: /<command> reload - reload configuration
